### ISSUE TITLE
Test Loss per epoch for parallel testing

### ISSUE THREAD

**Issue by sawhney-medha** [ultralytics/xview-yolov3#14]
I want to parallelly test the model and plot graphs for loss per epoch for the detections while testing. Can you please tell me how can I get the losses, since detect.py and score.py only give the mAP scores.

**Comment by glenn-jocher** [comment]
@sawhney-medha this repository is no longer maintained. I recommend you use https://github.com/ultralytics/yolov3 instead, which has numerous bug fixes and better instrospection tools.
