### ISSUE TITLE
analysis.m does not call make_small_chips() 

### ISSUE THREAD

**Issue by sawhney-medha** [ultralytics/xview-yolov3#15]
The matlab code analysis.m does not call make_small_chips() function anywhere. So to run the code, is the function call supposed to be uncommented or run without it?

**Comment by glenn-jocher** [comment]
make_small_chips() creates smaller images from each bounding box to pass to a second stage classifier.

Be advised that the https://github.com/ultralytics/xview-yolov3 repository is not under active development anymore. We recommend you use https://github.com/ultralytics/yolov3 instead, our main YOLOv3 repository.

**Comment by sawhney-medha** [comment]
@glenn-jocher Thank you for the prompt reply. I understand that it is not being updated but my work is specific to xview data hence I want to understand the working of this.
So if I want to train on my custom data or train on lesser classes do i need to call make_small_chips() while running analysis.m script or would the chips used for training will be taken care by datasets.py?

**Comment by glenn-jocher** [comment]
@sawhney-medha datasets.py selects chips from the available training data, you don't need make_small_chips(). make_small_chips() makes small chips from individual bounding boxes, some as small as 5x5 pixels for example, for a second stage classifier.

**Comment by sawhney-medha** [comment]
Okay. Thanks a lot for the help!

**Comment by glenn-jocher** [comment]
@sawhney-medha you're welcome! If you have any other questions, feel free to ask. Good luck with your project!
