### ISSUE TITLE
Augmentation in random_affine

### ISSUE THREAD

**Issue by sawhney-medha** [ultralytics/xview-yolov3#16]
Hello. Can you please explain how are the images being augmented in the random_affine() function in datasets.py. 

img1, labels1, M = random_affine(img0, targets=labels1, degrees=(-20, 20), translate=(0.01, 0.01), scale=(0.70, 1.30))

Thanks!

**Comment by glenn-jocher** [comment]
Hello, thank you for your interest in our work! `random_affine()` creates a random affine matrix to transform both the image and the bounding box coordinates simultaneously using a randomly selected set of parameters, including rotation, translation, skew, scale, etc. This data augmentation ensures the same image is never passed twice to training (in the exact same form), and helps train the network for increased robustness. You can find more details at https://github.com/ultralytics/yolov3#image-augmentation.

Also, please be advised that the https://github.com/ultralytics/xview-yolov3 repository is not under active development anymore. **We recommend you use https://github.com/ultralytics/yolov3 instead, our main YOLOv3 repository.**
