### ISSUE TITLE
Pixel coordinates

### ISSUE THREAD

**Issue by MhmdDimassi** [ultralytics/xview-yolov3#17]
Hello, **thank you for this project!**
I am working on a project related to building detection from satellite images using YoloV3, and i  think xView dataset is a big data with many labeling boxes, and this make it great for my project.
But a i want to clarify some basic question related to the coordinates of Bounding Box, when part of them look negative and decimal "in geojson file" , so i think it is not a pixel coordinates,
So, can you clarify this point and how to work with such coordinates or transform it to pixel coordinates (relative coordinates from top-left) ?
Thank you!

**Comment by glenn-jocher** [comment]
@MhmdDimassi all your dataset related questions should be answered on the view dataset site:çhttps://challenge.xviewdataset.org/welcome

**Comment by MhmdDimassi** [comment]
OK, thank you

**Comment by sainivedh** [comment]
@MhmdDimassi Hey, could you find any info on the negative or x_max,y_max>img_width,img_height annotations ?!
