### ISSUE TITLE
class weight hard mining

### ISSUE THREAD

**Issue by yangxu351** [ultralytics/xview-yolov3#19]
Hello, I know this repo is not under active, but I want to reproduce the repo on xview, could you please explain how did you get the hard mining class weight in utils/utils.py?
![Screenshot from 2019-12-25 17-18-28](https://user-images.githubusercontent.com/12199053/71450991-f9c14200-273a-11ea-949d-b37d7b6649e4.png)

**Comment by glenn-jocher** [comment]
@yangxu351 inverse frequency weights.

**Comment by yangxu351** [comment]
> @yangxu351 inverse frequency weights.

Thanks for your quick reply. But I feel a little confusing, the xview class weights are obtained according to the inverse  frequency of each class, are the xview_class_weights_hard_mining also obtained according to the inverse frequency weights? What's the difference? Or anything I wrongly understood?
![2019-12-27 (5)](https://user-images.githubusercontent.com/12199053/71538204-2c169f00-28f5-11ea-8daf-d7c2375a31ec.png)

**Comment by yangxu351** [comment]
@glenn-jocher Thanks for your quick reply. But I feel a little confusing, the xview class weights are obtained according to the inverse frequency of each class, are the xview_class_weights_hard_mining also obtained according to the inverse frequency weights? What's the difference? Or anything I wrongly understood?
![2019-12-27 (5)](https://user-images.githubusercontent.com/12199053/71538410-6cc3e780-28f8-11ea-850a-4cfb1220af72.png)

**Comment by glenn-jocher** [comment]
@yangxu351 this may refer to image or chip weighting, which deals with how often to present a given image or chip for learning. What you are showing above are the class weights, which are inverse frequencies.

**Comment by glenn-jocher** [comment]
@yangxu351 in any case, I do not recommend using this repo, as https://github.com/ultralytics/yolov3 is much better performing and currently maintained. You can train COCO from scratch to 61.4 mAP for example on it, better than darknet.

**Comment by yangxu351** [comment]
@glenn-jocher Thanks.

**Comment by glenn-jocher** [comment]
@yangxu351 you're welcome! If you have further questions, feel free to ask.
