### ISSUE TITLE
Not able to load images

### ISSUE THREAD

**Issue by abidmalikwaterloo** [ultralytics/xview-yolov3#2]
I am trying to run the model. However, I am getting the following error:

[amalik@node04 xview-yolov3]$ python train.py 
Namespace(batch_size=8, cfg='cfg/c60_a30symmetric.cfg', epochs=999, img_size=800, resume=False)
Traceback (most recent call last):
  File "train.py", line 207, in <module>
    main(opt)
  File "train.py", line 49, in main
    dataloader = ListDataset(train_path, batch_size=opt.batch_size, img_size=opt.img_size, targets_path=targets_path)
  File "/home/amalik/OGA/ultralytics/xview-yolov3/utils/datasets.py", line 64, in __init__
    assert self.nB > 0, 'No images found in path %s -- testing' % path
AssertionError: No images found in path ../train_images/train_images -- testing

I am confused, why it could not detect the images.

you can see that I have the images in this particular director
--------------
[amalik@node04 xview-yolov3]$ ls ../train_images/train_images/
100.tif   1106.tif  1208.tif  1397.tif  1467.tif  1625.tif  180.tif   18.tif    2012.tif  217.tif   2353.tif  2484.tif  2559.tif  324.tif  43.tif   552.tif  637.tif  765.tif  888.tif
102.tif   1109.tif  1211.tif  1399.tif  1468.tif  1630.tif  1810.tif  1900.tif  2014.tif  2181.tif  2354.tif  2485.tif  2560.tif  325.tif  445.tif  556.tif  639.tif  766.tif  889.tif
1036.tif  110.tif   1212.tif  1403.tif  1469.tif  1633.tif  1815.tif  1902.tif  2017.tif  2193.tif  2355.tif  2486.tif  2561.tif  331.tif  451.tif  557.tif  641.tif  767.tif  88.tif
1037.tif  1114.tif  1216.tif  1405.tif  1472.tif  163.tif   1817.tif  1904.tif  2020.tif  2197.tif  2356.tif  2487.tif  2562.tif  333.tif  455.tif  559.tif  647.tif  768.tif  892.tif
1042.tif  1118.tif  1217.tif  1406.tif  1473.tif  1647.tif  1818.tif  1906.tif  2021.tif  2207.tif  2359.tif  2489.tif  2564.tif  33.tif   457.tif  561.tif  650.tif  769.tif  893.tif
1044.tif  111.tif   1224.tif  140.tif   1476.tif  1649.tif  181.tif   1907.tif  2026.tif  2214.tif  2361.tif  2490.tif  2565.tif  340.tif  462.tif  562.tif  652.tif  772.tif  894.tif
1046.tif  1120.tif  1233.tif  1416.tif  1478.tif  1651.tif  1820.tif  1908.tif  2029.tif  2215.tif  2365.tif  2493.tif  2567.tif  342.tif  463.tif  563.tif  658.tif  774.tif  895.tif
1048.tif  1121.tif  1237.tif  1418.tif  1482.tif  1653.tif  1821.tif  1910.tif  2031.tif  2225.tif  2370.tif  2495.tif  2568.tif  343.tif  464.tif  567.tif  659.tif  777.tif  89.tif
1049.tif  1124.tif  1244.tif  1420.tif  1486.tif  1654.tif  1823.tif  1912.tif  2032.tif  2230.tif  2371.tif  2497.tif  2571.tif  345.tif  465.tif  568.tif  665.tif  781.tif  8.tif
104.tif   1125.tif  1245.tif  1422.tif  1487.tif  1656.tif  1824.tif  1913.tif  2036.tif  2237.tif  2373.tif  2498.tif  2573.tif  355.tif  469.tif  569.tif  669.tif  788.tif  903.tif
1050.tif  1126.tif  1246.tif  1425.tif  1496.tif  1673.tif  1825.tif  1914.tif  203.tif   2239.tif  2375.tif  2499.tif  2574.tif  360.tif  46.tif   574.tif  670.tif  791.tif  905.tif
1051.tif  1127.tif  124.tif   1428.tif  149.tif   1675.tif  1827.tif  1918.tif  2042.tif  223.tif   237.tif   24.tif    2584.tif  362.tif  473.tif  575.tif  671.tif  792.tif  907.tif
1052.tif  1128.tif  1253.tif  1429.tif  1505.tif  1677.tif  1828.tif  1919.tif  2044.tif  2242.tif  2382.tif  2503.tif  2587.tif  370.tif  474.tif  579.tif  672.tif  794.tif  90.tif
1053.tif  1129.tif  1255.tif  142.tif   1507.tif  1679.tif  1829.tif  1920.tif  2053.tif  2247.tif  2384.tif  2504.tif  2589.tif  371.tif  47.tif   580.tif  674.tif  79.tif   910.tif
1056.tif  112.tif   1256.tif  1430.tif  1508.tif  1690.tif  1831.tif  1921.tif  2055.tif  2250.tif  2386.tif  2505.tif  2591.tif  372.tif  481.tif  584.tif  680.tif  802.tif  914.tif
1058.tif  1132.tif  125.tif   1431.tif  1509.tif  1692.tif  1832.tif  1922.tif  2062.tif  2251.tif  2387.tif  2507.tif  2596.tif  373.tif  484.tif  587.tif  682.tif  805.tif  91.tif
105.tif   1133.tif  1265.tif  1432.tif  1511.tif  1694.tif  1834.tif  1926.tif  2064.tif  2261.tif  2389.tif  2509.tif  2599.tif  374.tif  486.tif  593.tif  684.tif  807.tif  924.tif
1061.tif  1135.tif  1268.tif  1436.tif  1523.tif  1695.tif  1838.tif  1927.tif  2072.tif  2264.tif  238.tif   2510.tif  2606.tif  375.tif  488.tif  594.tif  692.tif  80.tif   926.tif
1063.tif  1136.tif  126.tif   1438.tif  1529.tif  1701.tif  1840.tif  1928.tif  2078.tif  2268.tif  2391.tif  2511.tif  2608.tif  377.tif  492.tif  595.tif  694.tif  813.tif  927.tif
1065.tif  1139.tif  1278.tif  1439.tif  1530.tif  1702.tif  1841.tif  1929.tif  2094.tif  2269.tif  2398.tif  2513.tif  2609.tif  378.tif  493.tif  596.tif  69.tif   814.tif  928.tif
1067.tif  1140.tif  1280.tif  1440.tif  1559.tif  1703.tif  1845.tif  1930.tif  20.tif    2270.tif  2399.tif  2514.tif  2618.tif  379.tif  494.tif  598.tif  708.tif  815.tif  92.tif
1068.tif  1141.tif  1284.tif  1441.tif  1562.tif  1707.tif  1847.tif  1931.tif  2106.tif  2278.tif  2400.tif  2515.tif  2619.tif  380.tif  498.tif  5.tif    709.tif  817.tif  930.tif
106.tif   1142.tif  1285.tif  1442.tif  1565.tif  1739.tif  1848.tif  1932.tif  2108.tif  2279.tif  2405.tif  2516.tif  282.tif   381.tif  500.tif  600.tif  711.tif  819.tif  931.tif
1070.tif  1149.tif  128.tif   1443.tif  1568.tif  1740.tif  1849.tif  1938.tif  2110.tif  2281.tif  2408.tif  2518.tif  283.tif   382.tif  506.tif  601.tif  712.tif  822.tif  942.tif
1072.tif  1150.tif  129.tif   1444.tif  1577.tif  1741.tif  1855.tif  193.tif   2112.tif  2292.tif  2413.tif  2519.tif  285.tif   386.tif  509.tif  604.tif  716.tif  825.tif  946.tif
1076.tif  1154.tif  1309.tif  1445.tif  1579.tif  1743.tif  1856.tif  1940.tif  2114.tif  2293.tif  2414.tif  2520.tif  287.tif   389.tif  510.tif  605.tif  720.tif  836.tif  94.tif
1077.tif  1155.tif  130.tif   1446.tif  157.tif   1749.tif  1858.tif  1945.tif  2115.tif  2294.tif  2416.tif  2521.tif  289.tif   38.tif   512.tif  606.tif  724.tif  837.tif  959.tif
1079.tif  1158.tif  1311.tif  1447.tif  1580.tif  1767.tif  1863.tif  1961.tif  2118.tif  2301.tif  2421.tif  2523.tif  291.tif   393.tif  513.tif  608.tif  727.tif  838.tif  95.tif
107.tif   1164.tif  131.tif   1448.tif  1581.tif  1768.tif  1870.tif  1963.tif  2122.tif  2303.tif  2423.tif  2524.tif  293.tif   394.tif  517.tif  609.tif  72.tif   83.tif   960.tif
1080.tif  1165.tif  1327.tif  1449.tif  1584.tif  1769.tif  1875.tif  1964.tif  2124.tif  2305.tif  2425.tif  252.tif   294.tif   399.tif  520.tif  610.tif  732.tif  847.tif  962.tif
1081.tif  1169.tif  1329.tif  144.tif   1585.tif  1770.tif  1880.tif  1972.tif  2125.tif  2306.tif  2436.tif  2530.tif  295.tif   401.tif  521.tif  611.tif  734.tif  84.tif   968.tif
1084.tif  1175.tif  1346.tif  1450.tif  1586.tif  1772.tif  1881.tif  1973.tif  2128.tif  2308.tif  2438.tif  2531.tif  296.tif   407.tif  523.tif  612.tif  735.tif  859.tif  97.tif
1085.tif  1178.tif  1351.tif  1451.tif  1587.tif  1782.tif  1883.tif  1976.tif  2130.tif  2309.tif  2440.tif  2532.tif  302.tif   40.tif   525.tif  613.tif  73.tif   860.tif  983.tif
1086.tif  1180.tif  1353.tif  1452.tif  158.tif   1783.tif  1886.tif  1980.tif  2131.tif  2310.tif  2454.tif  2538.tif  303.tif   414.tif  529.tif  614.tif  740.tif  862.tif  986.tif
1087.tif  1181.tif  1357.tif  1453.tif  1590.tif  1784.tif  1887.tif  1982.tif  2139.tif  2313.tif  2455.tif  2541.tif  307.tif   415.tif  531.tif  615.tif  741.tif  863.tif  996.tif
1088.tif  1182.tif  1361.tif  1454.tif  1593.tif  1786.tif  1888.tif  1983.tif  2142.tif  2314.tif  2459.tif  2542.tif  309.tif   418.tif  532.tif  617.tif  742.tif  86.tif   99.tif
1089.tif  1184.tif  1362.tif  1456.tif  159.tif   1787.tif  1889.tif  1985.tif  2145.tif  2315.tif  2460.tif  2543.tif  310.tif   41.tif   534.tif  618.tif  744.tif  870.tif
1090.tif  1185.tif  1364.tif  1457.tif  1600.tif  1788.tif  1891.tif  1987.tif  2148.tif  2316.tif  2462.tif  2544.tif  311.tif   422.tif  535.tif  619.tif  74.tif   871.tif
1091.tif  118.tif   136.tif   1459.tif  1602.tif  1789.tif  1892.tif  1988.tif  2150.tif  2318.tif  2468.tif  2545.tif  315.tif   423.tif  537.tif  620.tif  752.tif  87.tif
1092.tif  1192.tif  1372.tif  145.tif   1604.tif  1795.tif  1893.tif  2000.tif  2159.tif  2320.tif  2469.tif  2547.tif  317.tif   42.tif   538.tif  621.tif  756.tif  880.tif
1094.tif  1193.tif  1374.tif  1460.tif  1606.tif  1799.tif  1894.tif  2004.tif  2160.tif  2322.tif  2470.tif  254.tif   31.tif    430.tif  53.tif   622.tif  75.tif   883.tif
1095.tif  1196.tif  1378.tif  1462.tif  1607.tif  1801.tif  1896.tif  2008.tif  2162.tif  2325.tif  2471.tif  2550.tif  320.tif   432.tif  540.tif  626.tif  760.tif  884.tif
109.tif   1197.tif  1379.tif  1463.tif  1608.tif  1806.tif  1897.tif  2009.tif  2168.tif  2326.tif  2472.tif  2552.tif  321.tif   433.tif  541.tif  627.tif  761.tif  885.tif
10.tif    1205.tif  1384.tif  1465.tif  1610.tif  1807.tif  1898.tif  2010.tif  216.tif   2334.tif  2475.tif  2555.tif  322.tif   434.tif  546.tif  629.tif  763.tif  886.tif
1104.tif  1206.tif  1385.tif  1466.tif  1624.tif  1809.tif  1899.tif  2011.tif  2179.tif  2341.tif  2482.tif  2557.tif  323.tif   437.tif  548.tif  635.tif  764.tif  887.tif

**Comment by glenn-jocher** [comment]
@abidmalikwaterloo yes this is true, the repo is set to find and load *.bmp training images. *.bmp images load significantly faster than *.tif images during training, so before training I run this function once to convert all *.tif to *.bmp. Then the repository works without issue:

https://github.com/ultralytics/xview-yolov3/blob/75406f093c7da3bf53d5f5507a5ad3ab3f347424/utils/datasets.py#L356-L366

**Comment by abidmalikwaterloo** [comment]
@glenn-jocher Thanks. What about "jpeg"?  how should I convert jpeg to bmp? Is there an utility for this?
