### ISSUE TITLE
RuntimeError: expected dtype Byte but got dtype Bool

### ISSUE THREAD

**Issue by manapshymyr-OB** [ultralytics/xview-yolov3#20]
What does this error mean? I wanted to train xview dataset
![Screenshot from 2020-02-19 14-54-13](https://user-images.githubusercontent.com/61227498/74817888-dc1dec80-5327-11ea-9009-691a199361f9.png)

**Comment by glenn-jocher** [comment]
@manapshymyr-OB note this repo is no longer actively supported. We recommend this for the most up to date object detection:
https://github.com/ultralytics/yolov3
