### ISSUE TITLE
About this yolo-v3

### ISSUE THREAD

**Issue by stevenalexis** [ultralytics/xview-yolov3#21]
@glenn-jocher ,Hi, Can I use this version-"xview-yolov3" to train and inference on coco2014 or coco2017 dataset.
It looks more succinct.

Thank you for your excellent codes.

**Comment by glenn-jocher** [comment]
Sure. For 2017:
```bash
git clone https://github.com/ultralytics/yolov3
bash yolov3/data/get_coco2017.sh  # 19GB
cd yolov3
pip install -U -r requirements.txt
python train.py --data coco2017.data
```

For 2014:
```bash
git clone https://github.com/ultralytics/yolov3
bash yolov3/data/get_coco2014.sh  # 19GB
cd yolov3
pip install -U -r requirements.txt
python train.py --data coco2014.data
```

**Comment by stevenalexis** [comment]
@glenn-jocher Thanks a lot.

**Comment by glenn-jocher** [comment]
@stevenalexis sure. Just to be clear, these commands use our main yolov3 repo, not this repo. https://github.com/ultralytics/yolov3

**Comment by stevenalexis** [comment]
@glenn-jocher thanks for your advice.

**Comment by glenn-jocher** [comment]
@stevenXS you're welcome! Feel free to reach out if you have any more questions. Good luck with your training!
