### ISSUE TITLE
Weights is unable to download

### ISSUE THREAD

**Issue by kumar045** [ultralytics/xview-yolov3#23]
Before submitting a bug report, please ensure that you are using the latest versions of:
 - Python
 - PyTorch
 - This repository (run `git fetch && git status -uno` to check and `git pull` to update)
 
**Your issue must be reproducible on a public dataset (i.e COCO) using the latest version of the repository, and you must supply code to reproduce, or we can not help you.**

If this is a custom training question we suggest you include your `train*.jpg`, `test*.jpg` and `results.png` figures.

## To Reproduce
**REQUIRED**: Code to reproduce your issue below
```
python train.py ...
```

## Environment

 - OS: [e.g. Ubuntu]
 - GPU [e.g. 2080 Ti]

**Comment by kumar045** [comment]
wget https://storage.googleapis.com/ultralytics/xview_best_lite.pt
wget https://storage.googleapis.com/ultralytics/xview_fresh9_5_e201.pt
link is not working

**Comment by glenn-jocher** [comment]
@kumar045 hi, thanks for the bug report! Yes, we recently removed these weights from our GCP bucket, and we are no longer maintaining this repository.

I would highly recommend using our new https://github.com/ultralytics/yolov5, featuring faster, lighter and more accurate object detection. YOLOv5 is recommended for all new projects, and is a good replacement for the YOLOv3 models used here.
