### ISSUE TITLE
How to merge tiled inference results? 

### ISSUE THREAD

**Issue by ok4d4** [ultralytics/xview-yolov3#24]
## Question

Hello, how do you merge the inference results in the NMS method?

**Comment by glenn-jocher** [comment]
@ok4d4 small objects detected twice in overlapping regions of tiles are automatically merged in NMS. There is nothing special required, simply normal NMS.

**Comment by ok4d4** [comment]
Isn't there a possibility that objects may not be detected if they are on the boundary of the grid?

**Comment by glenn-jocher** [comment]
@ok4d4 there's a possibility that objects may not be detected at all locations in the image.

**Comment by ok4d4** [comment]
Of course you're right.
When cropping an image, should I overlap parts of it?

**Comment by glenn-jocher** [comment]
@ok4d4 yes that's what I mean, if you overlap for example 10% each direction on a 640 crop, then all objects smaller than 64 pixels across should be detected at least once without any breaks. Larger objects may be cut in pieces, but then again the standard use case for sliding window inference is for detecting small objects in large images, so large objects should be less of an issue.
