### ISSUE TITLE
Perform object detection on tile-splitted video as well

### ISSUE THREAD

**Issue by pikachu28** [ultralytics/xview-yolov3#27]
## 🚀 Feature

Just like taking tiled image as an input we are able to detect the object, it would be great if the same thing could happen for tile-splitted .mp4 videos as well.

## Motivation

Most of the resource I am coming across over the internet deals with tiled images. I am searching for couple of days the same thing for videos but couldn't found anything.

## Pitch

I want this repository to detect objects in tiled .mp4 videos as well

I hope I made myself clear, if not please let me know.

**Comment by glenn-jocher** [comment]
@pikachu28 hi there! Thanks for the suggestion. I appreciate the interest in extending the object detection capabilities to tiled .mp4 videos. This feature would indeed be beneficial for many users. I'll bring this up with the Ultralytics team for consideration. If you'd like to explore some workarounds in the meantime, the Ultralytics Docs at docs.ultralytics.com may have some helpful resources. Thank you for your valuable input!
