### ISSUE TITLE
download_weights.sh no longer functional

### ISSUE THREAD

**Issue by cameron-a-johnson** [ultralytics/xview-yolov3#32]
## 🐛 Bug
download_weights.sh is no longer functional. It appears the files may have moved or been deleted.

## To Reproduce
**REQUIRED**: Code to reproduce your issue below
```
./download_weights.sh
```

## Expected behavior
```
--2022-02-28 17:13:57--  https://storage.googleapis.com/ultralytics/xview_best_lite.pt
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.73.208, 142.250.65.80, 142.250.188.208, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.73.208|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-28 17:13:57 ERROR 404: Not Found.
```

## Environment

OS: Ubuntu

**Comment by glenn-jocher** [comment]
@cameron-a-johnson hi there! Thanks for letting us know about this issue. We've recently reorganized our weights and models, and it looks like the download script hasn't been updated to reflect these changes. 

To resolve this, you can use the `python -m wget https://ultralytics.com/xview_best_lite.pt` command to download the desired file. If you have any other questions or need further assistance, please feel free to ask. We appreciate your understanding and patience as we work to improve our resources.
