### ISSUE TITLE
xView yolov3 weights .pt file download 404 error

### ISSUE THREAD

**Issue by taesanbeck** [ultralytics/xview-yolov3#38]
I am working in Google Colab Pro and using the A100 40GB GPU:
 - Python - Python 3.10.12
 - PyTorch -2.1.0+cu118
 - I haven't forked and cloned the repo yet. Do I need to get the .pt training weights?
 - I just want the weights .pt file so I can use it for transfer learning or retraining using my custom images dataset (we are still annotating in RoboFlow), and we want to retrain these weights using YOLOV8 and our new dataset for fine-tuning.
 
**Your issue must be reproducible on a public dataset (i.e COCO) using the latest version of the repository, and you must supply code to reproduce, or we can not help you.---- 
I just opened the repo and copied the weights file URLs into my code like this
<img width="682" alt="image" src="https://github.com/ultralytics/xview-yolov3/assets/63169589/ff7ae19d-e24b-422c-96f6-e9e982a894dc">

## 🐛 Bug
when I go to the .pt weight file URLs using wget or a browser I get a 404 error saying there is nothing there.

## To Reproduce (See attached image of Colab notebook)
```
%pip install -U ultralytics
%pip install wget

import wget

url = 'https://storage.googleapis.com/ultralytics/xview_best_lite.pt'
filename = wget.download(url)
```
```
python train.py --- Not applicable 

Yet, but I want to do something like:
model = YOLO('xview_best_lite.pt')  then train my new model with your pre-trained weights

```

## Expected behavior
I expected to see the xview_best_lite.pt in my colab current directory

## Environment
Google Colab Pro

 - Colab is a Linux Terminal
 - GPU A100 Tesla

## Additional context
I am a Data Analytics Engineering Masters Student at George Mason University working on a Class project, so any help you can provide would be great. Here is our Draft Abstract, but not finding a pre-trained model .pt file for the xView dataset is really holding us up; our other option is just to keep annotating (which is tough with so few people on the team).

## Project Abstract
The World Bank estimates Ukrainian reconstruction and recovery costs surpassed 411 billion dollars only one year after Russia's invasion [1]. Additionally, UNESCO reported 291 cultural sites destroyed as of September 2023 [2]. Timely and accurate infrastructure assessment and prioritized reconstruction will be pivotal in Ukraine’s post-war reconstruction efforts, with the damage cost exponentially increasing each year the war continues. Rapid building damage assessment will become critical for humanitarian efforts and post-war reconstruction. In 2022, the United Nations Development Program built a machine learning application that used Natural Language Processing to mine Building Damage Assessments from text reports on social media. The Program development team stated accurate classification of infrastructure status saves time with “information processing” and “prioritization” [3]. Scale AI additionally developed a dataset specifically for classifying three categories of building Damage, “No Damage,” “Damaged," and” Destroyed,” only for 310 square Km of the City of Mariupol. Their polygon dataset is open source, but the model weights used to train their semantic segmentation of Mariupol are proprietary and only cover Damage from March 2022. In the future, humanitarian assistance and government agencies will need an open-source, free way to track building damage throughout the conflict. This study aims to merge the latest in Computer Vision Technology, satellite imagery, and database applications to develop a web application to detect and database damaged and undamaged buildings in several key cities throughout Ukraine. The end state of this project is research that supports future United Nations and Humanitarian reconstruction efforts and potentially allows future developers a free model and dataset to help identify the “Damaged” and “Undamaged” state of buildings throughout Ukraine. Our research underscores the importance of accurate computer vision predictions of war-torn cities throughout Ukraine. This project contributes to government and humanitarian organizations and enhances the future development of Computer vision assistance to infrastructure assessment technologies.

**Comment by glenn-jocher** [comment]
@taesanbeck it seems like you're trying to download the xview_best_lite.pt weights file, but you're receiving a 404 error because the URL you used is incorrect. To resolve this, you should use the correct URL for the weights file.

To download the weights file, you can use the wget or any other preferred method to properly retrieve it. Once you have the .pt file, you can then use it for transfer learning or retraining with your custom dataset using YOLOv3.

Additionally, if you're looking to fine-tune the pre-trained weights with your new dataset, you can use the YOLO class provided by Ultralytics and pass the path to your downloaded weights file as a parameter.

I hope this helps! If you have any further questions or run into any issues, feel free to ask. Good luck with your project!

**Comment by taesanbeck** [comment]
@glenn-jocher thanks for the follow up. It seems I am using the wrong url, but I just copy pasted from the yolov3 repo on your gitHub, do I need to fork it to get the correct url, please keep in mind I literally started programming 18months ago. Additionally, you mentioned I could just pass the weights to the YOLO Class for YOLO v8 which is what I wanted to do before, so thanks. The question is where can I get the correct url? I can see you are pointing me in the right direction without just giving me the answer, which is what I need to get better so thanks, but I am still feeling slightly dumb like I missed something obvious, so feel free to throw me another hint while I look back through my code. -Thanks again

**Comment by glenn-jocher** [comment]
No problem at all, @taesanbeck! You don't need to fork the repo to get the correct URL. I understand that starting out might feel overwhelming, but it's great to see your dedication to learning and improving.

To get the correct URL for the weights file, you can visit the Ultralytics YOLOv3 repository on GitHub and navigate to the "Releases" section. There, you'll find the release containing the weights file you're looking for. Simply click on the release and you should be able to access the correct URL for the .pt file.

I'm glad to hear that you found the information about using the YOLO class helpful. It's a great tool for working with YOLOv8 and your custom dataset.

Keep exploring and learning, and don't hesitate to reach out if you have further questions. You're doing great!
