### ISSUE TITLE
unable to reproduce the results

### ISSUE THREAD

**Issue by abidmalikwaterloo** [ultralytics/xview-yolov3#5]
I am trying to reproduce the results. I am using one P100 and K80 GPU. 

I am using the following settings:

targets_path = 'utils/targets_c60.mat'

parser = argparse.ArgumentParser()
parser.add_argument('-epochs', type=int, default=300, help='number of epochs')
parser.add_argument('-batch_size', type=int, default=8, help='size of each image batch')
parser.add_argument('-cfg', type=str, default='cfg/c60_a30symmetric.cfg', help='cfg file path')
parser.add_argument('-img_size', type=int, default=32 * 19, help='size of each image dimension')
parser.add_argument('-resume', default=False, help='resume training flag')
opt = parser.parse_args()
print(opt)

The total loss is starting with 2300 and drop to 780 after 70 epochs. I was expecting around 700 at the start and dropping around 300 after 70 epochs based on the graphs on the website.

**Comment by glenn-jocher** [comment]
Hi @abidmalikwaterloo. Thanks for running the code. The absolute value of the loss is not very important, what's important is the shape of the loss curve.

The absolute value of the Precision and Recall is important though, do these track similarly? Can you post a picture of your loss plots here? You can make your own plots with the `plotResults()` function:
https://github.com/ultralytics/xview-yolov3/blob/75406f093c7da3bf53d5f5507a5ad3ab3f347424/utils/utils.py#L510-L521

**Comment by abidmalikwaterloo** [comment]
@glenn-jocher Thanks for the quick reply.
![figure_1](https://user-images.githubusercontent.com/447056/48294747-43c26800-e454-11e8-8372-40ad1152bfb2.png)

This is for 70 epochs. The model is still running. I ran with K80 as well and was not able to reproduce

**Comment by abidmalikwaterloo** [comment]
precision and recall graphs are very close to the actual results.  I am not an AI person.

**Comment by glenn-jocher** [comment]
Looks great, everything is fine!
