### ISSUE TITLE
Error during  training

### ISSUE THREAD

**Issue by abidmalikwaterloo** [ultralytics/xview-yolov3#7]
I am getting the following error:
```
Traceback (most recent call last):
  File "train_20_4_05lr.py", line 217, in <module>
    main(opt)
  File "train_20_4_05lr.py", line 123, in main
    for i, (imgs, targets) in enumerate(dataloader):
  File "/gpfshome01/u/amalik/OGA/Yolov3/xview-yolov3/utils/datasets.py", line 289, in __next__
    img_all = np.stack(img_all)[:, :, :, ::-1].transpose(0, 3, 1, 2)  # BGR to RGB and cv2 to pytorch
  File "/sdcc/u/amalik/.local/lib/python3.5/site-packages/numpy/core/shape_base.py", line 349, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```
I am using 31 images for training.  in datasets.py, the img_all array becomes empty.

**Comment by abidmalikwaterloo** [comment]
@glenn-jocher  Thanks. I solved it. Actually, the code uses the following:
```
self.shuffled_vector = np.random.choice(self.mat['image_numbers'].ravel(), self.nF,
                                                p=self.mat['image_weights'].ravel())
```
It always generates a list of 847 images in the dataset and related probability for p.  I was using a subset of the 847 images. The code was still producing the list of 847 images which naturally calling some files which were in the subset and causing the above error. Now, if I use the subset, do I have to produce "targets_c60.mat" file again? My understanding is Yes. But I would like to hear your comments on this.

**Comment by glenn-jocher** [comment]
No, it should be fine. The mat file contains the targets for each image. For example if image 10 is loaded the targets for it can be found in the mat file. If images are missing their targets simply won't be pulled from the loaded mat file.

**Comment by abidmalikwaterloo** [comment]
@byiringiro88 As I mentioned:

```
self.shuffled_vector = np.random.choice(self.mat['image_numbers'].ravel(), self.nF,
                                                p=self.mat['image_weights'].ravel())
```

**Comment by glenn-jocher** [comment]
@abidmalikwaterloo this issue is resolved in our main YOLOv3 repository:
https://github.com/ultralytics/yolov3

We are not actively developing the https://github.com/ultralytics/xview-yolov3 repository anymore, so I would transition to the one above and adapt that to your needs.
